on:
  push:
    branches:
      - main
#  pull_request:
#    branches:
#      - main
name: Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      #          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.3
        with:
#          appId firebase
          appId: ${{secrets.APPID_FIREBASE}}
#          firebase login:ci
          token: ${{secrets.TOKEN_FIREBASE}}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk